# Add Source information
insert into Source(C_source)
	values ('neg control'),
			('L-Arabinose'),
			('N-Acetyl-D-Glucosamine'),
			('D-Saccharic acid'),
			('Succinic acid'),
			('D-Galactose'),
			('L-Aspartic acid'),
			('L-Proline'),
			('D-Alanine'),
			('D-Trehalose'),
			('D-Mannose'),
			('Dulcitol'),
			('D-Serine'),
			('D-Sorbitol'),
			('Glycerol'),
			('L-Fucose'),
			('D-Glucuronic acid'),
			('D-Gluconic acid'),
			('DL-a-Glycerol Phosphate'),
			('D-Xylose'),
			('L-Lactic acid'),
			('Formic acid'),
			('D-Mannitol'),
			('L-Glutamic acid'),
			('D-Glucose-6-Phosphate'),
			('D-Galactonic acid-g-Lactone'),
			('DL-Malic acid'),
			('D-Ribose'),
			('Tween 20'),
			('L-Rhamnose'),
			('D-Fructose'),
			('Acetic acid'),
			('a-D-Glucose'),
			('Maltose'),
			('D-Melibiose'),
			('Thymidine'),
			('L-Asparagine'),
			('D-Aspartic acid'),
			('D-Glucosaminic acid'),
			('1,2-Propanediol'),
			('Tween 40'),
			('a-Ketoglutaric acid'),
			('a-Ketobutyric acid'),
			('a-Methyl-D-Galactoside'),
			('a-D-Lactose'),
			('Lactulose'),
			('Sucrose'),
			('Uridine'),
			('L-Glutamine'),
			('m-Tartaric acid'),
			('D-Glucose-1-Phosphate'),
			('D-Fructose-6-Phosphate'),
			('Tween 80'),
			('a-Hydroxyglutaric acid-g-Lactone'),
			('a-Hydroxybutyric acid'),
			('b-Methyl-D-Glucoside'),
			('Adonitol'),
			('Maltotriose'),
			('2`-Deoxyadenosine'),
			('Adenosine'),
			('Gly-Asp'),
			('Citric acid'),
			('m-Inositol'),
			('D-Threonine'),
			('Fumaric acid'),
			('Bromosuccinic acid'),
			('Propionic acid'),
			('Mucic acid'),
			('Glycolic acid'),
			('Glyoxylic acid'),
			('D-Cellobiose'),
			('Inosine'),
			('Gly-Glu'),
			('Tricarballylic acid'),
			('L-Serine'),
			('L-Threonine'),
			('L-Alanine'),
			('Ala-Gly'),
			('Acetoacetic acid'),
			('N-Acetyl-D-Mannosamine'),
			('Mono-Methylsuccinate'),
			('Methylpyruvate'),
			('D-Malic acid'),
			('L-Malic acid'),
			('Gly-Pro'),
			('p-Hydroxyphenyl Acetic acid'),
			('m-Hydroxyphenyl Acetic acid'),
			('Tyramine'),
			('D-Psicose'),
			('L-Lyxose'),
			('Glucuronamide'),
			('Pyruvic acid'),
			('L-Galactonic acid-g-Lactone'),
			('D-Galacturonic acid'),
			('Phenylethylamine'),
			('2-Aminoethanol');

# Add Media information
insert into Media(media) 
	values ('sBMS'), ('MP');